name: KukaCabinet

env:
  numEnvs: 256
  envSpacing: 1.5
  episodeLength: 500

  cabinet_pos_init: [0.05, 0.0, 0.45]
  cabinet_pos_delta: [0.075, 0.075, 0.05]

  numProps: 4

  obs_type: oracle

  dofVelocityScale: 0.1
  actionScale: 7.5

  fingerDistRewardScale: 0.04
  thumbDistRewardScale: 0.08
  aroundHandleRewardScale: 0.0
  openBonusRewardScale: 2.0
  goalDistRewardScale: 6.0
  openPoseRewardScale: 0.0
  goalBonusRewardScale: 2.0
  actionPenaltyScale: 0.01

  asset:
    assetRoot: "assets"
    assetFileNameKuka: "urdf/kuka_allegro_description/kuka_allegro.urdf"
    assetFileNameCabinet: "urdf/sektion_cabinet_model/urdf/sektion_cabinet_2.urdf"

sim:
  substeps: 1
  physx:
    num_threads: 4
    solver_type: 1
    num_position_iterations: 12
    num_velocity_iterations: 1
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False

task:
  randomize: False
